name: actions for poky

on:
  push:
    branches: ["master"]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: checkout poky
        uses: actions/checkout@v3
        with:
          repository: 'yoctoproject/poky'
          ref: 'yocto-4.0.7'
      - name: install build host packages
        run: |
          sudo apt update
          sudo apt -y install gawk wget git diffstat unzip texinfo gcc build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint xterm python3-subunit mesa-common-dev zstd liblz4-tool
      - name: initialize build host environment
        run: |
          DISTRO=poky-tiny && source ./oe-init-build-env
          echo 'BB_SIGNATURE_HANDLER = "OEEquivHash"' >> conf/local.conf
          echo 'BB_HASHSERVE = "auto"' >> conf/local.conf
          echo 'BB_HASHSERVE_UPSTREAM = "hashserv.yocto.io:8687"' >> conf/local.conf
          echo 'SSTATE_MIRRORS ?= "file://.* https://sstate.yoctoproject.org/all/PATH;downloadfilename=PATH"' >> conf/local.conf
          cat conf/local.conf
          bitbake core-image-minimal
      - name: Archive image dir artifact
        uses: actions/upload-artifact@v3
        with:
          name: images
          path: /home/runner/work/poky/poky/build/tmp/deploy/images

